export const SIDEBAR_COLLAPSED_WIDTH = 72
export const SIDEBAR_EXPANDED_WIDTH = 240

export const MAIN_CONTENT_COLLAPSED_OFFSET = SIDEBAR_COLLAPSED_WIDTH
export const MAIN_CONTENT_EXPANDED_OFFSET = SIDEBAR_EXPANDED_WIDTH
